# Generated by Django 4.2.13 on 2024-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="门店名")),
                ("location", models.CharField(max_length=200, verbose_name="地点")),
                ("phone_number", models.CharField(max_length=20, verbose_name="电话")),
                ("manager", models.CharField(max_length=100, verbose_name="负责人")),
            ],
            options={
                "verbose_name": "门店信息",
                "verbose_name_plural": "门店信息",
            },
        ),
    ]
