# Generated by Django 4.2.13 on 2024-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="stores", to="supplier.supplier", verbose_name="供货商"
            ),
        ),
    ]
