# Generated by Django 4.2.13 on 2024-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "supplier",
            "0002_alter_supplier_address_alter_supplier_contact_person_and_more",
        ),
        ("store", "0002_store_suppliers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Store ID"
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="store",
            name="manager",
            field=models.CharField(max_length=100, verbose_name="Manager"),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Store Name"),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="store",
            name="suppliers",
            field=models.ManyToManyField(
                related_name="stores", to="supplier.supplier", verbose_name="Suppliers"
            ),
        ),
    ]
