# Generated by Django 4.2.13 on 2024-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="供货商名")),
                ("phone_number", models.CharField(max_length=20, verbose_name="电话")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("contact_person", models.CharField(max_length=40, verbose_name="联系人")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
            ],
            options={
                "verbose_name": "供货商信息",
                "verbose_name_plural": "供货商信息",
            },
        ),
    ]
