# Generated by Django 4.2.13 on 2024-06-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.CharField(max_length=200, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(max_length=40, verbose_name="Contact Person"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Supplier ID"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Supplier Name"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
    ]
