# Generated by Django 4.2.13 on 2024-06-23 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_orders_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={
                "ordering": ["-confirm"],
                "verbose_name": "订单信息",
                "verbose_name_plural": "订单信息",
            },
        ),
    ]
